# Intro to NumPy

In [1]:
import numpy as np

## Datatypes and Attributes

### NumPy array creation and basic attributes

We use NumPy to create arrays. Arrays are similar to lists, but they can be multi-dimensional.
NumPy arrays are faster and more efficient than lists.

In [2]:
# Numpy's main datatype is ndarray - n-dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [9]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],  # 3D array - useful for images
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [4]:
a2

array([[1, 2],
       [3, 4]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.shape  # Displays (3,) - 1D array with 3 elements

(3,)

In [15]:
a2.shape  # Displays (2, 3) - 2D array with 2 rows and 3 columns

(2, 3)

In [16]:
a3.shape  # Displays (2, 3, 3) - 3D array with 2 layers, 3 rows and 3 columns

(2, 3, 3)

In [17]:
a1.ndim, a2.ndim, a3.ndim  # Displays (1, 2, 3) - number of dimensions

(1, 2, 3)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [19]:
a1.size, a2.size, a3.size  

(3, 6, 18)

In [21]:
type(a1), type(a2), type(a3) # Python function to check the type of an object. ndarray's are universal data types

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Dataframe Creation

In [23]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5